### ISSUE TITLE
Fails to format ERB templates only containing ERB tags

### ISSUE THREAD

**Issue by marcuslilja** [adamzapasnik/prettier-plugin-erb#10]
I have a `.html.erb` template file with the following contents:

```erb
<%= content_tag :div, 'Content' %>
```

Running prettier with the plugin would reformat the file to only contain a tag looking like `<eext1 />`. It is possible to mitigate the problem by adding a wrapper element or reformat the template to look like this:

```erb
<%= content_tag :div do %>
  Content
<% end %>
```

Any idea on how to fix single line templates without the use of blocks?

**Comment by adamzapasnik** [comment]
Hey thanks for the issue. I have a fix for that, I will release it this week.

**Comment by marcuslilja** [comment]
> Hey thanks for the issue. I have a fix for that, I will release it this week.

Perfect, thanks!

**Comment by kieranklaassen** [comment]
Appreciate it! This is such a great find! I was looking for this for years! Thanks @adamzapasnik

**Comment by tmaier** [comment]
I just ran into the same problem. Is there by any chance a branch to try out the possible fix?
