### ISSUE TITLE
Option to prevent automatic tag closing?

### ISSUE THREAD

**Issue by leastbad** [adamzapasnik/prettier-plugin-erb#15]
I have a scenario where I individually render three partials, roughly corresponding to `<ul>`, a collection of `<li></li>` and a `</ul>`. These three strings are then concatenated to produce a result. (Yes, it's much more complex in reality, but this gets the idea across, hopefully.)

The problem is that when running `prettier-plugin-erb`, it decides that I forgot to close my `<ul>` and silently fixes it for me - breaking my list.

Is there a way to suppress automatic closing tag creation? Even on an explicit exception list basis?

**Comment by adamzapasnik** [comment]
Hi. If I understand correctly, this is the (simplified) problem:

Input
```html
<ul>
```

Output
```html
<ul></ul>
```

And in your case `</ul>` is in another partial, so you don't want it to be appended here?

**Comment by leastbad** [comment]
Yes, exactly.

It's an atypical scenario, but not unthinkable.

FWIW, this behaviour is really handy for 99.5% of templates! But there's no hard rule that the DOM fragment expressed in an ERB template has to be closed at EOF.

**Comment by adamzapasnik** [comment]
Actually, I have been aware of this issue :sweat_smile: But it's such a rare case that I didn't do anything about it.

Here is related prettier issue: https://github.com/prettier/prettier/issues/5665 It seems that we will have to come up with this option on our own.

I'm looking into possible solutions right now, but I don't think I will be able to release a fix this month. Expect it next month.

For now, just add the affected files to `.prettierignore` :bow: Hopefully, it's not a deal breaker.

**Comment by leastbad** [comment]
Actually, `.prettierignore` **is** the fix, Adam. I'm serious.

Thank you for reminding me that it exists. This should be the way forward for this kind of weirdo edge case.

Have a great weekend, and thanks for this library.
